name: Cypress
on:
  push:
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  basic-ubuntu-16:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout:latest

      - name: Cypress tests
        uses: cypress-io/github-action:latest
