name: Cypress Test
on:
  push:
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  cypress-test:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - uses: actions/checkout@master

      - name: Install Cypress and verify
        run: |
          npm ci
          ($npm bin)/cypress verify

      - name: Run cypress tests
        run: npm run test:chrome
        continue-on-error: false

      - name: Copy test execution videos and screenshots
