name: Cypress
on:
  push:
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  basic-ubuntu-16:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 14
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - run: yarn build

      - name: Cypress tests
        uses: cypress-io/github-action@master
        with:
          command: npm run e2e:ci
          wait-on: 'http://localhost:3000'
