name: Cypress Test
on:
  push:
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  cypress-test:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 14
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile

      - name: Run cypress tests
        run: npm run e2e:ci
        continue-on-error: false
