name: Unit Tests
on:
  push:
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Jest
        uses: stefanoeb/jest-action@master
        continue-on-error: false
